# Generated by Django 2.2.19 on 2021-02-21 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=30)),
                ('site', models.CharField(max_length=50, verbose_name='Site')),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tecido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('rendimento', models.FloatField(verbose_name='Rendimento')),
                ('estampa', models.BooleanField(default=False, verbose_name='Estampado')),
                ('estampa_exclusiva', models.BooleanField(default=False, verbose_name='Estampa Exclusiva')),
                ('medida', models.CharField(choices=[('KG', 'Kg'), ('MT', 'MT')], default='MT', max_length=2)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_estoque.Fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(verbose_name='Quantidade')),
                ('data_compra', models.DateTimeField(verbose_name='Data da Compra')),
                ('data_entrega', models.DateTimeField(verbose_name='Data da entrega')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_estoque.Fornecedor')),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_estoque.Representante')),
                ('tecido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_estoque.Tecido')),
            ],
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='representante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_estoque.Representante'),
        ),
    ]
