# Generated by Django 2.2.19 on 2021-02-21 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle_estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='representante',
            options={'verbose_name': 'Representante', 'verbose_name_plural': 'Representantes'},
        ),
        migrations.AlterModelOptions(
            name='tecido',
            options={'verbose_name': 'Tecído', 'verbose_name_plural': 'Tecídos'},
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='representante',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='controle_estoque.Representante'),
        ),
    ]
