# Generated by Django 2.2.19 on 2021-02-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_estoque', '0002_auto_20210221_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecido',
            name='medida',
            field=models.CharField(choices=[('KG', 'Kg'), ('MT', 'MT')], default='METROS', max_length=2),
        ),
    ]
