# Generated by Django 2.2.19 on 2021-02-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_estoque', '0003_auto_20210221_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_compra',
            field=models.DateField(verbose_name='Data da Compra'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_entrega',
            field=models.DateField(verbose_name='Data da entrega'),
        ),
        migrations.AlterField(
            model_name='tecido',
            name='medida',
            field=models.CharField(choices=[('KG', 'Kg'), ('MT', 'MT')], default='METROS', max_length=2, verbose_name='Unidade Medida'),
        ),
    ]
